# Generiert von Kivy Designer am 2025-06-12 11:13:12

<GeneratedLayout>:
    Slider:
        pos: 50, 200
        size: 100, 50
        size_hint: None, None
        text: "Test Button"
    Slider:
        pos: 200, 200
        size: 100, 50
        size_hint: None, None
        text: "Test Label"
    Slider:
        pos: 50, 100
        size: 150, 50
        size_hint: None, None
        min: 0
        max: 100
        value: 50